### PR TITLE
Add Python 3 Support

### PR DESCRIPTION
**Pull request by AlexVerrico**
As Python 2 has now officially reached End Of Life (https://www.python.org/doc/sunset-python-2/), and Octoprint supports Python 3 as of Release 1.4.0, all plugins are encouraged to add Python 3 compatibility, which is what I have done in this pull request.

A brief summary of the changes that I made:

 - Added the plugin property __plugin_pythoncompat__ = ">=2.7,<4"
 - Updated the plugin version to 0.0.5

This update has being tested and confirmed to work in both Python 2.7 and 3.7 using Octoprint 1.4.0 running on Octopi 0.17.0

Cheers,
Alex.

### CODE REVIEW

**Comment by AlexVerrico** [comment]
Any update here @MoonshineSG?

**Comment by MoonshineSG** [comment]
Check the updates

**Comment by AlexVerrico** [comment]
@MoonshineSG So you copied the changes rather than merging my PR?

**Comment by MoonshineSG** [comment]
Didn’t copy them, but put al the changes like in almost all my other plugins. Is there a difference?

**Comment by AlexVerrico** [comment]
@MoonshineSG Just generally good practice to merge PRs instead of copying, as some people will take offence at this. Since I can see that you have made the changes though, I will close this PR.

**Pull request closed without merging**
